language: "ru"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      language: "ru"
      author:
        name: "Саша Сорокин"
        role: "Проверяющий команды по переводу Discord на русский язык"
        avatar: "https://avatars2.githubusercontent.com/u/10401817?s=100&v=4"
  - scope:
      path: "docs/translation"
      type: pages
    values:
      category: "волонтёрство"
  - scope:
      path: "docs/guides"
      type: pages
    values:
      category: "руководства"

copyright:
  license: "CC-BY 4.0"
  additional_material: /COPYRIGHT-NOTICES

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions

compress_images:
  images_path: "{docs,assets}/**/*.{gif,png,jpg,jpeg,svg}"

exclude_pages:
  - 404.html
  - sitemap.xml
  - robots.txt
  - redirects.json
  - feed.xml

hamburger_links:
  - title: about
    url: about
  - title: contribute
    is_edit: Yes
